# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be518388b9c95005b03ee097d85533a4baf209a2cdfbcadb68729f317a5895d0e56066f7a061e067620f20bf6681e7766659cb795bb9529d08e5e82280258d46

test:
  secret_key_base: d40c4e8a487d78388dce78bab600f4249eed4e3b790f7d5e7e2877937b284e49f312d7add49fda05d9d436c2ade634dd50d9c7f7f2fc03cbd371e93cc3dfb37f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
